Us3 page d accueil
WildCodeSchool/0523-RemFr-JavaAngular-P1-artetloire pull request #14
Opened 2023-06-16 14:37 UTC by Kuroshin-28

Si j'ai fais de la merde :
1. Me dire : "Baptiste ! T'as fais de la merde !"
2. Accepter la Pull Request
3. Me demander de changer mon pseudo Discord en "J'ai fait de la merde 💩 "

2023-06-16 14:46 UTC, Matthieu28 approved these changes

2023-06-16 14:48 UTC, Matthieu28 approved these changes
max-width est en px 👀

2023-06-19 06:16 UTC, bastienapp requested changes

2023-06-19 06:16 UTC, bastienapp commented on src/app/components/carousel/carousel.component.ts
> +    }, 5000);
ça serait bien de mettre les 5000 ms dans une constante, ex : 

private readonly SLIDER_TIME_MS = 5000;

2023-06-19 06:16 UTC, bastienapp commented on src/app/app.module.ts
> +    AccueilPageComponent,
ça serait bien de changer le nom du fichier et des appels en anglais, ex : HomeComponent

2023-06-19 09:38 UTC, bastienapp approved these changes
Top, je valide :+1:

2023-06-19 09:40 UTC, bastienapp commented
Attention, tu as fermé la Pull Request sans la fusionner (c'était peut-être voulu ?)

2023-06-19 09:42 UTC, Kuroshin-28 commented
Oui, j'ai encore fais de la merde pour changer, j'ai laissé des commentaires dans le code.

2023-06-19 09:46 UTC, bastienapp approved these changes

2023-06-20 07:16 UTC, merged